# Generated by Django 3.1.5 on 2021-01-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20210124_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='twitter_url',
        ),
    ]
